### ISSUE TITLE
Creating table instances should also load `hudi-defaults.conf`

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#111]
During `crates/core/src/table/mod.rs:96 load_configs<I, K, V>`, hudi global configs (a `hudi-defaults.conf` file loaded in dir specified by `HUDI_CONF_DIR` env var) should be loaded as well.

**Comment by gohalo** [comment]
i could work on that if no one plan for.

As [externalized-config-file](https://hudi.apache.org/cn/docs/configurations#externalized-config-file) described , should scan all files under HUDI_CONF_DIR directory, and maybe filter with *.conf.

And i havn't found the format of this file, maybe properties, ini etc. Just got some ideas from [Hudi Issues #5291](https://github.com/apache/hudi/issues/5291), like the following.

```
# Default system properties included when running Hudi jobs.
# This is useful for setting default environmental settings.

# Example:
hoodie.datasource.write.table.type                      COPY_ON_WRITE
hoodie.datasource.write.hive_style_partitioning         false
```

**Comment by xushiyan** [comment]
@gohalo great! as per the linked doc, only `hudi-defaults.conf` should be loaded under `HUDI_CONF_DIR`. The format should be like a conf file as you showed or delimited by `=` like

```
hoodie.datasource.write.recordkey.field=uuid
```

**Comment by zzhpro** [comment]
> @gohalo great! as per the linked doc, only `hudi-defaults.conf` should be loaded under `HUDI_CONF_DIR`. The format should be like a conf file as you showed or delimited by `=` like
> 
> ```
> hoodie.datasource.write.recordkey.field=uuid
> ```

There is a template file at https://github.com/apache/hudi/blob/master/conf/hudi-defaults.conf.template,  in which keys and values aren't delimited by `=` . Should we follow the format there?
