### ISSUE TITLE
Support `CREATE EXTERNAL TABLE` using DataFusion

### ISSUE THREAD

**Issue by gohalo** [apache/hudi-rs#125]
Just like the java client routies.

```
HoodieTableMetaClient.withPropertyBuilder()
        .setTableType(HoodieTableType.MERGE_ON_READ)
        .setTableName(tableName)
        .setTableCreateSchema(SCHEMA)
        .setPayloadClassName(HoodieAvroPayload.class.getName())
        .initTable(conf, tablePath);
```

Currently, got some problems.

1. object_store crate doesn't support to create directory. Because of the [struct Path](https://github.com/apache/arrow-rs/blob/678517018ddfd21b202a94df13b06dfa1ab8a378/object_store/src/path/mod.rs#L130) which without leading or trailing delimiters.

```
pub struct Path {
    /// The raw path with no leading or trailing delimiters
    raw: String,
}
```

But in most of cloud object store including minio, you could put empty to some path like `/data/example/.hoodies/`. Maybe we could change the value of private raw in the `struct Path` with `unsafe` codes, or, create some marker files like `.hoodies/.schema/marker`.

2. We should create compatiable config files for Java properties, especilly for `hoodies.properties`.

**Comment by xushiyan** [comment]
we are not prioritizing write support at this moment. let's pivot this issue to support `create external table` in datafusion https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table

@jonathanc-n are you interested in picking this up? would you share some high-level implementation points?

**Comment by jonathanc-n** [comment]
High level implementation: 
- Have tableproviderfactory validate parameters for creating an instance of `CreateExternalTable`. 
- Since we are currently focusing on read capabilities, add a read only table type and use that to create the table

**Comment by jonathanc-n** [comment]
For example, https://github.com/apache/hudi-rs/blob/main/crates/datafusion/src/lib.rs#L291 has a solid test or the functionality. What functionality would you like to target on top of this?

**Comment by xushiyan** [comment]
@jonathanc-n you're right, i almost forgot this is actually a dup of https://github.com/apache/hudi-rs/issues/150 we should update the readme to reflect the usage, and add a module example to show this in datafusion/lib.rs

**Comment by xushiyan** [comment]
Closing this due to being a dup. @jonathanc-n pls feel free to file a PR to update the docs if you're keen. I'll keep a todo for myself also for an overall docs update before working on the release.

> @jonathanc-n you're right, i almost forgot this is actually a dup of #150 we should update the readme to reflect the usage, and add a module example to show this in datafusion/lib.rs
