### ISSUE TITLE
Upgrade arrow-rs, object_store, datafusion, pyo3 versions

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#143]
Upgrade the dependencies, and resolve any build issue.

**Comment by kazdy** [comment]
@xushiyan can you assign me to it please, that would be a good opportunity for me to get more familiar with the codebase

**Comment by xushiyan** [comment]
@kazdy there you go! do you think you can get this within these 2 days? trying to cut 0.2.0 branch within the week

**Comment by kazdy** [comment]
I'll try to deliver it asap

**Comment by kazdy** [comment]
@xushiyan seems like we should wait for datafusion to bump their dependencies, we're using the latest datafusion and
it depends on arrow `^52.2.0` (so can't bump to `53.0`), object_store `^0.11.2` so we can't bump it to `0.11.0`, same goes for py3o.

Looks like it's best for the next datafusion release and upgrade these dependencies at that time.
What do you think?

**Comment by xushiyan** [comment]
@kazdy sounds good. let's wait then.

**Comment by xushiyan** [comment]
@kazdy looks like there were some patch releases for these libs - would you be able to submit a PR to update to those patch versions? likely nothing will break - just getting some improvements for the next release :)

**Comment by kazdy** [comment]
@xushiyan ready in #168
