### ISSUE TITLE
Create `HudiTableFactory` implementing DataFusions `TableProviderFactory`

### ISSUE THREAD

**Issue by matthewmturner** [apache/hudi-rs#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

This isnt a bug report - its a feature request but i didnt see a way to submit a feature request.

I would like to be able to register hudi tables with datafusion like so:

```
CREATE EXTERNAL TABLE my_table STORED AS HUDITABLE LOCATION '/path/to/table';
```

If hudi-rs provided a `TableProviderFactory` then we could register and use that (This is how i [currently](https://github.com/datafusion-contrib/datafusion-dft/blob/main/src/extensions/deltalake.rs) register deltalake tables and I would like to do something similar for hudi).

### Steps To Reproduce

Not a bug

### Expected behavior

I can register tables to datafusion like so:

```
CREATE EXTERNAL TABLE my_table STORED AS HUDITABLE LOCATION '/path/to/table';
```

### Software information

N/A

**Comment by xushiyan** [comment]
@matthewmturner thanks for raising this! would you be able to review the linked PR by @kazdy please?

**Comment by matthewmturner** [comment]
@xushiyan sure, checking it out

**Comment by matthewmturner** [comment]
Looks good but when i try [integrating](https://github.com/datafusion-contrib/datafusion-dft/pull/189) in my app i get the below error (which isnt surprising since we arent on the same version of datafusion).  Of course thats not a blocker for this though :). Excited to see this though

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/bbb9c805-6637-441a-acbf-17d7e694520e">

**Comment by xushiyan** [comment]
@matthewmturner we just landed this feature in main. can you pls test it out with your PR? note that we choose `HUDI` as the name to stay consistent. See https://github.com/apache/hudi-rs/pull/162#discussion_r1799914280. thanks.

**Comment by matthewmturner** [comment]
@xushiyan sure will do, do you have any recommendations for what test data to use?  i just need something simple to test a basic query

**Comment by xushiyan** [comment]
@matthewmturner yes we keep a bunch of zipped test tables in https://github.com/apache/hudi-rs/tree/main/crates/tests/data/tables

you can unzip and use them directly.

**Comment by matthewmturner** [comment]
Okay, going to work on this tonight / tomorrow.  I may ping you for a review if you dont mind.

**Comment by matthewmturner** [comment]
I must be doing something wrong, im getting error that `hoodie.properties` doesnt exist even though it does.

<img width="1726" alt="image" src="https://github.com/user-attachments/assets/4abdaf3c-fc26-4e9a-b900-3bad75ccad89">

will pick this up tomorrow.

**Comment by kazdy** [comment]
Hi Matt, 

I cloned your branch and got this:
<img width="889" alt="image" src="https://github.com/user-attachments/assets/c7559215-5177-4e48-92f5-5dbf82e55acc">
Can it be something related to your file permissions maybe?

**Comment by matthewmturner** [comment]
_sigh_ i got it to work.  the repo used to be called `datafusion-tui` and i still have it as that locally pointing to `datafusion-dft` so my path was wrong.

**Comment by matthewmturner** [comment]
and now test passes :)
