### ISSUE TITLE
Integrate with datafusion to support filters pushdown from SQL

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#160]
Follow-up feature of #47 

Integrate with datafusion on the predicate expression parsing and support pushdown predicates from SQL.

**Comment by jonathanc-n** [comment]
May I be assigned this?

**Comment by xushiyan** [comment]
@jonathanc-n sure. can you first elaborate on the changes you're gonna make? like what structs and APIs you'll introduce and some high level design to show how it works for the requirement?

**Comment by jonathanc-n** [comment]
Probably will involve these:
- Convert DataFusion's Expr objects into Hudi filters added in #119 . 
- Implement the supports_filters_pushdown method in the TableProvider.
- Change scan method to pass translated filters to Hudi's apis

**Comment by xushiyan** [comment]
@jonathanc-n sounds good
