### ISSUE TITLE
Partition filter against string or date field should  strip `'` around the value

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Partition filter currently works for `foo > A` for string field. To match sql syntax, it should be `foo > 'A'`.  But current logic won't trim the single quotes and take `'A'` as a whole for the value. Similarly for date types, it should parse `date = '2020-01-01'` correctly.

### Steps To Reproduce

Run with partition filters like `foo > A` for a string field, and `date = '2020-01-01'` for a date field.

### Expected behavior

Single quotes should be stripped for applicable field types.

### Software information

- Operating system:
- Rust version:
- Project version:

**Comment by xushiyan** [comment]
hey @KnightChess do you happen to have some time to work on this issue? hope to get this in 0.2.0

**Comment by KnightChess** [comment]
@xushiyan hi, sorry, I've been quite busy these past few weeks and haven't had time to follow up on this issue.

**Comment by xushiyan** [comment]
@KnightChess no problem

**Comment by kazdy** [comment]
@xushiyan please take a look at #170 I took an attempt to fix this
