### ISSUE TITLE
Support for Writing Hudi Table Format

### ISSUE THREAD

**Issue by baptvit** [apache/hudi-rs#225]
### Description of the improvement

I noticed while exploring the repository that it currently lacks functionality for writing Hudi tables. If there is an existing implementation or documentation that addresses this, I would appreciate if you could share the relevant links.

It would be highly beneficial to add support for writing Hudi tables using the current library to enhance its usability and adoption.

### Expected behavior

- Provide an API or utility within the library that allows users to write data in the Hudi table format.
- Include documentation and examples showcasing how to use this feature.

**Comment by jonathanc-n** [comment]
@baptvit Write support is being worked on in the future. Read support is being implemented before this. For more info for this you can refer to the roadmap: https://github.com/orgs/apache/projects/356.

**Comment by baptvit** [comment]
Got it, thanks @jonathanc-n. Closing the issue.
