### ISSUE TITLE
Enforce Python code style

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#5]
we should configure
- https://github.com/python/mypy
- https://github.com/astral-sh/ruff

in `pyproject.toml`

**Comment by muyihao** [comment]
Hi, I'd like to work on this issue.

**Comment by abyssnlp** [comment]
I can take this and #73 if required. Let me know.

**Comment by xushiyan** [comment]
@muyihao are you planning to start on this ?

**Comment by muyihao** [comment]
@xushiyan Yes, I am currently working on this issue. I will provide updates as I make progress. Thanks!
