### ISSUE TITLE
Add in-code docs for Rust

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#71]

**Comment by KnightChess** [comment]
does it meat add doc for every `Moudles`, `Sturct`, `Method` in code,
like this?
```rust 
/// Table interface for engine integrate
#[derive(Clone, Debug)]
pub struct Table {
    pub base_url: Arc<Url>,
    pub configs: Arc<HudiConfigs>,
    pub extra_options: Arc<HashMap<String, String>>,
    pub timeline: Timeline,
    pub file_system_view: FileSystemView,
}

```

**Comment by xushiyan** [comment]
@KnightChess that's correct. the goal is to make https://docs.rs/hudi/latest/hudi/ have docs

**Comment by KnightChess** [comment]
@xushiyan got it. I've been familiarizing myself with this project recently, and I can help contribute to this document.
