### ISSUE TITLE
Define Hudi error types across hudi-core

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#72]
Use `thiserror` to define error enums to fit different error handling flows, and replace `anyhow::Error` usage.

**Comment by xushiyan** [comment]
@codope any plan to resume the work? Updated the milestone/release date.

**Comment by gohalo** [comment]
does this still wip? while i try to add some create table methods, just found this is a little chaos.

maybe i will try to refact that.

**Comment by codope** [comment]
@gohalo Please go ahead with your refactoring. I can help with review. I had opened https://github.com/apache/hudi-rs/pull/59 to refactor error handling but it is incomplete and preferably we shall use [thiserror](https://docs.rs/thiserror/latest/thiserror/).

**Comment by gohalo** [comment]
Submit a pr, just replaced the anyhow package, but still have some problems to fix.

First, how to classified the errors.
1. User configurations, invalid file/object path, unsupported features.
2. Communication failed, mostly from the obejct_store crate.
3. Invalid hoodie table, including file layout, file format, crashed data file and so on. Including from parquet arrow crates.
4. and more.

Second, how to simplify the error generation or mapping process. `thiserror` provide many macros for this, such as `error` `from` etc. But still have many situation to simplify, through some trait like `Into`.
